name: Update Revision File

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  update_revision:
    runs-on: 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update revision.txt
        run: |
          echo "$(date)" >> revision.txt
          git add revision.txt
          git commit -m "Update revision.txt with timestamp" || echo "No changes to commit"
          git push
